apiVersion: skaffold/v2beta14
kind: Config
build:
  artifacts:
    - image: superm-k8s
      docker:
        dockerfile: devops/docker/Dockerfile
        noCache: false
deploy:
  kubectl:
    manifests:
      - devops/k8s/k8s-skaffold-local.yaml