apiVersion: apps/v1
kind: Deployment
metadata:
  name: superm-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: superm-k8s
  template:
    metadata:
      labels:
        app: superm-k8s
    spec:
      containers:
        - name: superm-k8s
          image: superm-k8s
          ports:
            - containerPort: 80
          env:
            - name: APP_PORT
              value: '80'
            - name: APP_ADDRESS
              value: 'http://supermetrics.sys'
---
apiVersion: v1
kind: Service
metadata:
  name: superm-k8s
  labels:
    app: superm-k8s
spec:
  selector:
    app: superm-k8s
  ports:
    - port: 80
      protocol: TCP
      name: superm-k8s
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: superm-k8s-ing
  annotations:
    nginx.ingress.kubernetes.io/redirect-regex: ^/(.*)
spec:
  rules:
    - host: supermetrics.sys
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: superm-k8s
                port:
                  name: superm-k8s